dist: xenial
language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip3 install requests mip coverage codecov

before_script:
  - SCRIPT=tikdb.py

script: python3 $SCRIPT || python $SCRIPT

after_success:
  - coverage run $SCRIPT
  - codecov
