dist: xenial
language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install requests coverage codecov mip

script: python tikdb.py

after_success:
  - coverage run tikdb.py
  - codecov
