dist: xenial  # python 3.7
language: python

python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - pip install requests mip coverage codecov

before_script:
  - SCRIPT=tikdb.py
script: python $SCRIPT

after_success:
  - coverage run $SCRIPT
  - codecov
